import type { PortfolioConfig } from '@/types/portfolio'

export const portfolioConfig: PortfolioConfig = {
  title: 'zhaijunhuai',
  personal: {
    name: '翟俊槐',
    nameEn: 'zunff',
    avatar: '/images/avatar.svg',
    bio: 'Java后端开发（具备AI Agent全栈开发经验）',
    techStack: [
      'Java',
      'Spring Boot',
      'Spring Cloud',
      'React',
      'Vue',
      'TypeScript',
      'PostgreSQL',
      'Docker',
      'AI Agent',
    ],
    social: {
      github: 'https://github.com/zunff',
      email: '1430119384@qq.com',
      phone: '13690927930',
    },
  },
  projects: [
    {
      id: 'interview-agent',
      title: 'AI Interview Agent',
      summary: '基于 Spring AI + LangGraph4j 的多模态 AI 面试系统，支持实时视频分析、智能追问',
      techStack: [
        'Java 21',
        'Spring Boot 3.4',
        'Spring AI',
        'LangGraph4j',
        'DashScope',
        'PostgreSQL',
        'pgvector',
        'WebSocket',
        'ReAct Agent',
      ],
      images: [
        '/images/projects/interview-agent/01-homepage.webp',
        '/images/projects/interview-agent/02-interview.webp',
        '/images/projects/interview-agent/03-interview-report.webp',
        '/images/projects/interview-agent/04-analysis-report.webp',
      ],
      description:
        '多模态 AI 面试系统 + 简历分析系统，采用 LangGraph4j 有向状态图架构编排面试流程。面试模块支持实时视频分析、Omni 多模态综合评估和智能追问；简历分析模块支持自动解析、多维度评分和 ReAct Agent 自由对话。\n\n核心架构：将面试流程建模为有向状态图，采用主图 + 批量题目生成子图 + 轮次子图的三层架构，并行生成题目节省约 60-70% 初始化时间。面试评估一次调用 Qwen-Omni 同时分析音频、视频帧、转录文本，按权重评分（语义75% / 语音15% / 视觉10%），根据回答质量动态选择追问策略（低分深入/高分挑战/普通追问）。\n\n简历分析采用两阶段架构：阶段一 LangGraph4j 自动化评估流水线（解析 → 公司调研 → 4维度并行评分 → 报告），阶段二 Spring AI ReAct Agent 自由对话，Agent 可调用文件解析和联网搜索工具。实时通信采用 REST + WebSocket + SSE 三通道。',
      github: 'https://github.com/zunff/interview-agent',
    },
    {
      id: 'ticket-booking-backend',
      title: '高并发抢票系统',
      summary: '基于 Spring Boot 3.2 + Java 21 虚拟线程的高并发抢票系统，支持 600+ QPS',
      techStack: [
        'Java 21',
        'Spring Cloud',
        'Redis',
        'Kafka',
        'Sentinel',
        'Kubernetes',
        'Prometheus',
      ],
      images: [
        '/images/projects/ticket-booking/01-homepage.webp',
        '/images/projects/ticket-booking/02-concert-detail.webp',
        '/images/projects/ticket-booking/03-booking-flow.webp',
        '/images/projects/ticket-booking/04-architecture.webp',
      ],
      description:
        '生产级高并发抢票系统后端，基于 Spring Cloud + Java 21 虚拟线程构建。采用 Redis Lua + Kafka + MySQL 最终一致性方案，核心抢票流程采用 Redis Lua 脚本实现原子化库存扣减和限购校验，配合 Kafka 异步消息队列解耦订单创建与数据库库存扣减。\n\n微服务架构拆分为 5 个核心服务（Gateway、User、Concert、Order、Stock），每个服务独立数据库，通过 Nacos 实现服务注册与发现。集成 Sentinel 实现用户维度限流、服务间调用熔断、Redis 操作熔断保护等多层次防护。Gateway 采用一致性哈希实现 Sticky Session，提升本地缓存命中率。\n\n性能优化成果：通过 Gateway JWT 缓存优化（99%+ 命中率）、JVM 参数调优（G1GC）、虚拟线程启用，在压测中实现 600/s QPS、P95 响应时间 2.78s、失败率仅 0.11%。支持 Kubernetes 部署，配置 HPA 自动扩缩容、Prometheus + Grafana 监控体系。',
      github: 'https://github.com/zunff/ticket-booking-backend',
    },
    {
      id: 'oj-backend-microservice',
      title: 'OJ 在线判题系统',
      summary: 'GitHub 68 ⭐️ 在线判题系统，Spring Cloud 微服务架构，集成代码沙箱与 API 开放平台',
      techStack: [
        'Java 8',
        'Spring Cloud',
        'Nacos',
        'Sentinel',
        'Seata',
        'RabbitMQ',
        'Redis',
        'Docker',
      ],
      images: [
        '/images/projects/oj-backend/01-login.webp',
        '/images/projects/oj-backend/02-question-list.webp',
        '/images/projects/oj-backend/03-code-edit.webp',
        '/images/projects/oj-backend/04-submit-history.webp',
        '/images/projects/oj-backend/05-create-question.webp',
      ],
      description:
        '完整的在线判题系统（Online Judge）。包含前端、微服务后端、API开放平台SDK、代码沙箱四个独立模块，覆盖从题目管理、代码提交、安全执行到判题结果反馈的完整闭环。\n\n微服务架构：拆分为网关、用户、题目、判题、开放平台 5 个核心服务，通过 Spring Cloud Gateway 统一入口，Nacos 服务注册与配置中心，各服务独立数据库。判题服务通过 RabbitMQ 异步处理判题请求，代码沙箱采用 Docker 容器隔离执行环境，限制资源使用防止恶意代码攻击，支持 Java、C++、Python 等多语言。\n\nAPI开放平台：开发了 Spring Boot Starter SDK，开发者引入依赖并配置 API Key 即可调用 OJ 平台能力（题目查询、代码提交、结果查询），SDK 内置签名验证、请求重试、错误处理。通过 Sentinel 限流熔断、Seata 分布式事务保证跨服务数据一致性、Redis 缓存热点数据。',
      github: 'https://github.com/zunff/oj-backend-microservice',
    },
    {
      id: 'zun-rpc',
      title: 'Zun-RPC 轻量级 RPC 框架',
      summary: '基于 Spring Boot Starter 的轻量级 RPC 框架，自定义 TCP',
      techStack: [
        'Java 11',
        'Spring Boot 2.6',
        'Netty',
        'Etcd',
        'Kryo',
        'Hessian',
        'Jackson',
        '自定义协议',
      ],
      images: [
        '/images/projects/zun-rpc/01-architecture.webp',
        '/images/projects/zun-rpc/02-protocol-format.webp',
        '/images/projects/zun-rpc/03-call-flow.webp',
      ],
      description:
        '轻量级 RPC 框架，采用 Spring Boot Starter 模式封装，通过声明式注解 @ZunRpcService / @ZunRpcReference 实现透明化远程调用。自定义了完整的 TCP 协议栈，基于 Netty 实现高性能通信层。\n\n自定义 17 字节定长协议头 + 变长 Body 的二进制协议，RequestId（雪花算法）实现单连接上的请求-响应多路复用。支持 JDK、Kryo、JSON、Hessian 四种序列化器，通过协议头标记区分。Netty 通信层内置连接池复用和心跳保活机制，Consumer 写空闲 30s 发送心跳，Provider 读空闲 60s 关闭连接。\n\n服务治理：支持 Etcd 注册中心（Watch 服务变更、心跳续期、优雅下线）和直连模式。负载均衡支持随机、轮询、一致性哈希三种策略。容错策略包括快速失败、安全失败、失败自动恢复、失败自动切换。核心组件均通过 `@Bean` + `@ConditionalOnMissingBean` 注册，支持用户自定义扩展。',
      github: 'https://github.com/zunff/zun-rpc',
    },
    {
      id: 'tank-battle-online',
      title: '坦克大战联机版',
      summary: '基于 JavaFX + Netty 的实时多人坦克大战游戏，支持 2-10 人联机对战',
      techStack: [
        'Java 17',
        'JavaFX',
        'Netty',
        'Protobuf',
        'Spring Boot',
        'gRPC',
        'MyBatis-Plus',
      ],
      images: [
        '/images/projects/tank-battle/01-in-game.webp',
        '/images/projects/tank-battle/02-game-lobby.webp',
        '/images/projects/tank-battle/03-room.webp',
        '/images/projects/tank-battle/04-architecture.webp',
      ],
      description:
        '完整的多人在线坦克大战游戏系统，包含 JavaFX 桌面客户端、Netty TCP 游戏服务器、Spring Boot 微服务后端和压测工具四个模块。支持 2-10 人同房间实时对战，涵盖坦克移动、射击、碰撞检测、地图破坏等完整游戏机制。\n\n自定义 TCP 二进制协议：15 字节定长协议头（Type + Version + RequestID + BodyLength + CRC32）+ Protobuf 消息体，CRC32 校验确保数据完整性。客户端采用 JavaFX Canvas 60 FPS 渲染，32x32 网格地图，支持可破坏墙壁、4 方向移动、音效系统。TCP 服务器实现 20 TPS 游戏时钟、AABB 碰撞检测、随机地图生成。\n\n系统架构：客户端通过 HTTP 登录获取 JWT Token，通过 TCP 自定义协议与游戏服务器实时通信，游戏服务器通过 gRPC 与后端服务交互验证 Token 和查询用户信息。内置压测工具支持多房间并发测试，模拟完整游戏流程。Netty NIO 异步 IO + 线程池优化 + 内存池管理，消息延迟 < 50ms。',
      github: 'https://github.com/zunff/tank-battle-online',
    },
  ],
}
